### ISSUE TITLE
GET THIS CHEAT BACK ALIVE

### ISSUE THREAD

**Issue by 2ez4JAG** [ericek111/java-csgo-externals#4]
^^^

**Comment by ericek111** [comment]
Hello,

this cheat was never dead. I was just too lazy to commit stuff.

There's a new release available, you can download it using the script. Feel free to contribute or suggest features.

I was thinking of making a mouse aimbot, but I just can't get the LocalClient (/EnginePointer/ClientState, whatever you call it). I'd really appreciate some help with that!
