### ISSUE TITLE
not working! 

### ISSUE THREAD

**Issue by citizen46** [ericek111/java-csgo-externals#8]
new update

**Comment by ericek111** [comment]
I know, I've already almost fully fixed it for myself.

In any case, I won't be providing any support for this project. I may or may not upload the most recent code to the wip branch. If I decide to do so, you're free to compile and use it, otherwise updating the cheat is your homework.

**Comment by citizen46** [comment]
Oie! i don't use this one just wanted to hear from you, as you helped me before on https://github.com/McSwaggens/linux-csgo-external/issues/55

**Comment by citizen46** [comment]
Help me already I've been busy with learning about this all, and at the end of today i'm empty hands and i believe you can help me with this one, i have no idea what exactly changed in this one
https://github.com/McSwaggens/linux-csgo-external

**Comment by ericek111** [comment]
They upgraded their compiler.

New signatures (they also changed some offsets):
```Java
public static String GLOWOBJECT_SIGNATURE = "E8 ?? ?? ?? ?? 48 8B 3D ?? ?? ?? ?? BE 01 00 00 00 C7";
public static String ALT1_SIGNATURE = "89 D8 80 CC 40 F6 C2 03 0F 45 D8 44 89 ?? C1 E0 11 C1 F8 1F 83 E8 03";
public static String OVERRIDEPOSTPROCESSINGDISABLE_SIGNATURE = "55 48 89 E5 41 57 41 56 41 55 41 54 53 48 81 EC ?? ?? ?? ?? 89 BD 18 FF FF FF 80 3D ?? ?? ?? ?? 00 89 B5 14 FF FF FF";
public static String CLIENTCLASSHEAD_SIGNATURE = "44 89 EA B8 01 00 00 00 44 89 E9 C1 FA 05 D3 E0 48 63 D2 41 09 04 91 48 8B 05 ?? ?? ?? ?? 8B 53 14 48 8B 00 48 85 C0 75 1B E9 F9 01 00 00";

long alt1mov = PatternScanner.getAddressForPattern(Engine.clientModule(), ALT1_SIGNATURE);
long alt1 = Engine.clientModule().GetAbsoluteAddress(alt1mov - 7, 3, 7);
long jump = alt1 - 0xC * 2;

long foundGlowPointerCall = PatternScanner.getAddressForPattern(Engine.clientModule(), GLOWOBJECT_SIGNATURE);
long glowFunctionCall = Engine.clientModule().GetCallAddress(foundGlowPointerCall);
m_dwGlowObject = Engine.clientModule().GetAbsoluteAddress(glowFunctionCall + 9, 3, 7);

long clientclassheadlea = PatternScanner.getAddressForPattern(Engine.clientModule(), CLIENTCLASSHEAD_SIGNATURE) + 23;
m_dwClientClassHead = Engine.clientModule().GetAbsoluteAddress(clientclassheadlea, 3, 7);
m_dwClientClassHead = Engine.clientModule().readLong(m_dwClientClassHead);
m_dwClientClassHead = Engine.clientModule().readLong(m_dwClientClassHead);

long overridepostprocessingdisablemov = PatternScanner.getAddressForPattern(Engine.clientModule(), OVERRIDEPOSTPROCESSINGDISABLE_SIGNATURE) + 26;
m_dw_bOverridePostProcessingDisable = Engine.clientModule().GetAbsoluteAddress(overridepostprocessingdisablemov, 2, 7);
```

**Comment by citizen46** [comment]
#1 Thank-you soo much for doing hard work for me <3
#2 I'm really thankful!
#3 I have no idea how to do this in https://github.com/McSwaggens/linux-csgo-external

**Comment by NisTa24** [comment]
Its not working please help me @citizen46

**Comment by NisTa24** [comment]
I even tried this one https://github.com/ericek111/linux-csgo-external-1 but still not working. Please help. plz

**Comment by ericek111** [comment]
That one is not up-to-date yet. In 2 hours or so. atm I'm working on this cheat.

**Comment by NisTa24** [comment]
Thanks a lot. You are the best!

**Comment by citizen46** [comment]
No joke this @ericek111 always helped me, a really good person.

**Comment by NisTa24** [comment]
Yeah he's a great coder.

**Comment by citizen46** [comment]
@ericek111 will you mind recording the screen about how you are going to update the code for https://github.com/McSwaggens/linux-csgo-external

I really do want to learn.

**Comment by NisTa24** [comment]
lets not trouble him much :)

**Comment by ericek111** [comment]
Thanks a lot, I appreciate the feedback. :) :D I take notes so I can find the offsets easier next time.

I will do it again and record it. Right now I've fixed the [InputOffsets](https://github.com/ericek111/java-csgo-externals/blob/wip/src/me/lixko/csgoexternals/offsets/InputOffsets.java) in this cheat by simply adding/subtracting from a known address and simply experimenting in CS:GO.

**Comment by ericek111** [comment]
Fixed: https://github.com/McSwaggens/linux-csgo-external/pull/49

And a horrible, really, really freaking awful, tutorial: https://youtu.be/3MOLnpd3NTM

+ closed, since it's not related to this repo.

**Comment by NisTa24** [comment]
Haha thanks bro.
